global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']

  - job_name: 'connect'
    static_configs:
      - targets: ['connect:9102']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
